name: container-images


on:
  workflow_dispatch:
  push:
    # branches: [ "main" ]
    # tags: [ "v*" ]
    #
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # - run: echo "IMAGE_TAG=dev" >> $GITHUB_ENV
    #   if: github.ref_name == 'main'
    # - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
    #   if: startsWith(github.ref, 'refs/tags/v')

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    #
    # - name: Login to docker.io
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_UID }}
    #     password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build and push image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}:dev

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.8.1

    - name: Sign container image
      shell: bash 
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
          cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}

    - name: Verify image signatures
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
          cosign verify \
            --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/build-container.yml@${{ github.ref }} \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            ghcr.io/${{ github.repository }}:dev
